# theme: jekyll-theme-minimal
theme: jekyll-theme-alembic
title: About Malin Consulting
description: Learn more about Malin Consulting's training programmes that will catapult you into your dream job.
